version: "3"
name: ecommerce-ms
services:
  # auth service
  auth:
    build: ./auth
    restart: always
    image: mukundjajadiya/auth
    depends_on:
      - mongodb
    command: yarn start
    volumes:
      - ./auth:/app
      - /app/node_modules
    ports:
      - "8001:8001"
    env_file:
      - ./auth/.env

  # order service
  order:
    build: ./order
    image: mukundjajadiya/order
    restart: always
    depends_on:
      - mongodb
    command: yarn start
    volumes:
      - ./order:/app
      - /app/node_modules
    ports:
      - "8002:8002"
    env_file:
      - ./order/.env

  # product service
  product:
    build: ./product
    image: mukundjajadiya/product
    restart: always
    depends_on:
      - mongodb
    command: yarn start
    volumes:
      - ./product:/app
      - /app/node_modules
    ports:
      - "8003:8003"
    env_file:
      - ./product/.env

  # mongodb service
  mongodb:
    build: /mongodb
    image: mukundjajadiya/mongodb
    restart: always
    ports:
      - "2717:27017"
    volumes:
      - mongodb:/data/db
    env_file:
      - /mongodb/.env

  # nginx (api-gateway) service
  nginx:
    build: /nginx
    image: mukundjajadiya/nginx
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
    depends_on:
      - auth
      - order
      - product
      - mongodb

volumes:
  mongodb:
